version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5430:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes:
      - ./data/postgres:/data